service: Jornada-Matte
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  httpApi:
    cors: true
  

# functions:
#   jornada-matte:
#     handler: handler.webhook
#     timeout: 30
#     events:
#       - httpApi:
#           path: /webhook
#           method: post

#   checker:
#     handler: handler.check_stages
#     timeout: 60
#     events:
#       - schedule: cron(0/10 11-21 ? * MON-FRI *)
    
#   validacao:
#     handler: handler.validacao_check
#     timeout: 60
#     events:
#       - schedule: cron(0 0 1,16 * ? *)

#   checkpoint:
#     handler: handler.checkpoint_check
#     timeout: 60
#     events:
#       - schedule: cron(0 0 1 * ? *)

#   dashboard:
#     handler: handler.dashboard
#     timeout: 60
#     events:
#       - schedule: rate(1 hour)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    pipCmdExtraArgs:
      - '--platform'
      - 'manylinux2014_x86_64'
      - '--python-version'
      - '3.11'
      - '--only-binary=:all:'
    slim: true